# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-20 15:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webgui', '0009_auto_20170720_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=5)),
                ('su', models.CharField(max_length=20)),
                ('architect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architect', to=settings.AUTH_USER_MODEL)),
                ('integrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='modal',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='modal',
        ),
        migrations.DeleteModel(
            name='Leisure',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Modal',
        ),
    ]
